### ISSUE TITLE
CUB数据集上复现报错

### ISSUE THREAD

**Issue by realfzyyyyy** [Markin-Wang/MixViT#2]
在使用MixViT-main/scripts/train_cub.sh复现mixvit时会报错：
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ml_collections/config_dict/config_dict.py", line 883, in __getitem__
    field = self._fields[key]
KeyError: 'resnet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ml_collections/config_dict/config_dict.py", line 807, in __getattr__
    return self[attribute]
  File "/usr/local/lib/python3.6/dist-packages/ml_collections/config_dict/config_dict.py", line 889, in __getitem__
    raise KeyError(self._generate_did_you_mean_message(key, str(e)))
**KeyError: "'resnet'"**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/data/private/MixViT-main/train.py", line 458, in <module>
    main()
  File "/opt/data/private/MixViT-main/train.py", line 451, in main
    args, model = setup(args)
  File "/opt/data/private/MixViT-main/train.py", line 102, in setup
    model = make_model(config, args, zero_head=True, num_classes=num_classes, vis=True)
  File "/opt/data/private/MixViT-main/models/make_model.py", line 94, in make_model
    model = build_transformer(config, args, zero_head=True, num_classes=num_classes, vis=True)
  File "/opt/data/private/MixViT-main/models/make_model.py", line 43, in __init__
    self.inter_arch = ResNetV2(block_units=config.resnet.num_layers,
  File "/usr/local/lib/python3.6/dist-packages/ml_collections/config_dict/config_dict.py", line 809, in __getattr__
    raise AttributeError(e)
**AttributeError: "'resnet'"**
请问是什么情况呢？

**Comment by Markin-Wang** [comment]
Hi, CUB上的实验是在纯ViT架构下做的，纯vit代码在[mixvit_purevit](https://github.com/Markin-Wang/MixViT/tree/main/mixvit_purevit)，请在纯vit目录下运行train_cub.sh脚本。

**Comment by realfzyyyyy** [comment]
好的！感谢 ^_^&nbsp;



---原始邮件---
发件人: "Jun ***@***.***&gt;
发送时间: 2023年5月12日(周五) 下午5:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Markin-Wang/MixViT] CUB数据集上复现报错 (Issue #2)




 
Hi, CUB上的实验是在纯ViT架构下做的，纯vit代码在mixvit_purevit，请在纯vit目录下运行train_cub.sh脚本。

**Comment by realfzyyyyy** [comment]
> Hi, CUB上的实验是在纯ViT架构下做的，纯vit代码在[mixvit_purevit](https://github.com/Markin-Wang/MixViT/tree/main/mixvit_purevit)，请在纯vit目录下运行train_cub.sh脚本。

请问实验过程中使用了几张卡呢？单卡复现过程中结果始终与文中的差一点

**Comment by Markin-Wang** [comment]
> 

Hi, 实验是在2x2080Ti上做的。
